import Head from 'next/head';
import Image from 'next/image';
import Total from '../components/totals';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div>
        {/* Total components*/}
        <div>
          <Total />
        </div>
        {/* table # charts components*/}
        <div>
          <div className='flex'>
            <div className='flex-1 border-2'>R</div>
            <div className='flex-1 border-2'>L</div>
          </div>
        </div>
      </div>
    </div>
  );
}
