import Head from 'next/head';
import Image from 'next/image';
import Statewise from '../components/tableAndChart/Statewise';
import Total from '../components/totals';

export default function Home({ data }) {
  return (
    <div>
      {console.log(data)}
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div>
        {/* Total components*/}
        <div>
          <Total totalC={data} />
        </div>
        {/* table # charts components*/}
        <div>
          <div className='md:flex'>
            <div className='flex-1 mt-10'>
              <Statewise statewiseData={data} />
            </div>
            <div className='flex-1 mt-10'>L</div>
          </div>
        </div>
      </div>
    </div>
  );
}

export async function getServerSideProps() {
  const res = await fetch('https://api.covid19india.org/data.json');
  const data = await res.json();

  return {
    props: {
      data,
    },
  };
}
// https://data.covid19india.org/state_district_wise.json
